#!/bin/bash
set -e

GITLAB_CI_VERSION=7.8.0

INSTALL_DIR="/home/gitlab_ci/gitlab-ci"
DATA_DIR="/home/gitlab_ci/data"
LOG_DIR="/var/log/gitlab-ci"

SETUP_DIR="/app/setup"
GEM_CACHE_DIR="${SETUP_DIR}/cache"

# rebuild apt cache
apt-get update

# install build dependencies for gem installation
apt-get install -y gcc g++ make libc6-dev ruby2.1-dev \
  libmysqlclient-dev libpq-dev zlib1g-dev libyaml-dev libssl-dev \
  libgdbm-dev libreadline-dev libncurses5-dev libffi-dev \
  libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev

# add git user
adduser --disabled-login --gecos 'GitLab CI' gitlab_ci

# create the data store
sudo -u gitlab_ci -H mkdir -p ${DATA_DIR}

# shallow clone gitlab-ci
echo "Cloning gitlab-ci v.${GITLAB_CI_VERSION}..."
sudo -u gitlab_ci -H git clone -q -b v${GITLAB_CI_VERSION} --depth 1 \
  https://github.com/gitlabhq/gitlab-ci.git ${INSTALL_DIR}

cd ${INSTALL_DIR}

# copy default configurations
cp lib/support/nginx/gitlab_ci /etc/nginx/sites-available/gitlab_ci
sudo -u gitlab_ci -H cp config/application.yml.example config/application.yml
sudo -u gitlab_ci -H cp config/resque.yml.example config/resque.yml
sudo -u gitlab_ci -H cp config/database.yml.mysql config/database.yml
sudo -u gitlab_ci -H cp config/unicorn.rb.example config/unicorn.rb
sudo -u gitlab_ci -H cp config/initializers/smtp_settings.rb.sample config/initializers/smtp_settings.rb

# symlink log -> ${LOG_DIR}/gitlab-ci
rm -rf log
ln -sf ${LOG_DIR}/gitlab-ci log

# create required tmp directories
sudo -u gitlab_ci -H mkdir -p tmp/pids/ tmp/sockets/
chmod -R u+rwX tmp

# install gems required by gitlab-ci, use cache if available
if [ -d "${GEM_CACHE_DIR}" ]; then
  mv ${GEM_CACHE_DIR} vendor/
  chown -R gitlab_ci:gitlab_ci vendor/cache
fi
sudo -u gitlab_ci -H bundle install --deployment --without development test

# install cronjob
bundle exec whenever -w -u gitlab_ci RAILS_ENV=production

# make sure everything in /home/gitlab_ci is owned by the gitlab_ci user
chown -R gitlab_ci:gitlab_ci /home/gitlab_ci/

# install gitlab bootscript
cp lib/support/init.d/gitlab_ci /etc/init.d/gitlab_ci

# disable default nginx configuration and enable gitlab's nginx configuration
rm -f /etc/nginx/sites-enabled/default

# create the /var/run/sshd directory (required for sshd to start)
mkdir -p /var/run/sshd

# move supervisord.log file to ${LOG_DIR}/supervisor/
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisor/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# move nginx logs to ${LOG_DIR}/nginx
sed 's|access_log /var/log/nginx/access.log;|access_log '"${LOG_DIR}"'/nginx/access.log;|' -i /etc/nginx/nginx.conf
sed 's|error_log /var/log/nginx/error.log;|error_log '"${LOG_DIR}"'/nginx/error.log;|' -i /etc/nginx/nginx.conf

# configure supervisord log rotation
cat > /etc/logrotate.d/supervisord <<EOF
${LOG_DIR}/supervisor/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure gitlab-ci log rotation
cat > /etc/logrotate.d/gitlab-ci <<EOF
${LOG_DIR}/gitlab-ci/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure gitlab-ci vhost log rotation
cat > /etc/logrotate.d/gitlab-ci-vhost <<EOF
${LOG_DIR}/nginx/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord to start unicorn
cat > /etc/supervisor/conf.d/unicorn.conf <<EOF
[program:unicorn]
priority=10
directory=${INSTALL_DIR}
environment=HOME=/home/gitlab_ci
command=bundle exec unicorn_rails -c ${INSTALL_DIR}/config/unicorn.rb -E production
user=gitlab_ci
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# configure supervisord to start sidekiq
cat > /etc/supervisor/conf.d/sidekiq.conf <<EOF
[program:sidekiq]
priority=10
directory=${INSTALL_DIR}
environment=HOME=/home/gitlab_ci
command=bundle exec sidekiq -c {{SIDEKIQ_CONCURRENCY}}
  -q runner
  -q common
  -q default
  -e production
  -P ${INSTALL_DIR}/tmp/pids/sidekiq.pid
  -L ${INSTALL_DIR}/log/sidekiq.log
user=gitlab_ci
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# configure supervisord to start nginx
cat > /etc/supervisor/conf.d/nginx.conf <<EOF
[program:nginx]
priority=20
directory=/tmp
command=/usr/sbin/nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# configure supervisord to start crond
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=20
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# purge build dependencies
apt-get purge -y --auto-remove gcc g++ make libc6-dev ruby-dev \
  libmysqlclient-dev libpq-dev zlib1g-dev libyaml-dev libssl-dev \
  libgdbm-dev libreadline-dev libncurses5-dev libffi-dev \
  libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev

# cleanup
rm -rf /var/lib/apt/lists/*
